// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePage = "page"

// Page mapped from table <page>
type Page struct {
	ID          uint32    `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Title       string    `gorm:"column:title;not null;comment:文章标题" json:"title"`                                       // 文章标题
	Description string    `gorm:"column:description;not null;comment:文章描述" json:"description"`                           // 文章描述
	Author      string    `gorm:"column:author;not null;comment:文章作者" json:"author"`                                     // 文章作者
	Thumbnail   string    `gorm:"column:thumbnail;not null;comment:文章图片" json:"thumbnail"`                               // 文章图片
	Views       uint32    `gorm:"column:views;not null;comment:查看数量" json:"views"`                                       // 查看数量
	Content     *string   `gorm:"column:content;comment:文章内容" json:"content"`                                            // 文章内容
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:current_timestamp();comment:添加时间" json:"created_at"` // 添加时间
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;default:current_timestamp();comment:更新时间" json:"updated_at"` // 更新时间
}

// TableName Page's table name
func (*Page) TableName() string {
	return TableNamePage
}
